import {createSlice} from "@reduxjs/toolkit";

const countrySlice = createSlice({
    name: "country",
    initialState:  {
            countries: [{
                countryName: "",
                countryCode: ""
            }]
    },
    reducers: {
        // no ACTION_TYPES, this will internally create a type "user/addItem" that you will never use by hand. You will only see it in the devTools
        countrySelection: (state, action) => {
            if(!state.countries.includes(action.payload))
            state.countries.push(action.payload);
        }
    }
})

// autogenerated action creators
export const { countrySelection } = countrySlice.actions;

// and export the final reducer
export default countrySlice.reducer;
